name: Node.js CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-2016]
        node-version: [12.x, 14.x]
        
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - uses: actions/upload-artifact@master
      with:
          name: webpack artifacts
          path: public/
  test:
  
    need: [build]
    
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2016]
        node-version: [12x, 14x]
        
    steps:
      -uses: actions/checkout@v2
      uses: actions/download-artifact@main
      with:
          name: webpack artifacts
          path: public
      -name: Use Node.js ${{ matrix.node-version }}
      -uses: actions/setup-node@v1
      -with:
        node-version: ${{ matrix.node-version }}
      
      name: npm install, and test
      run: |
          npm install
          npm test
      env:
        CI: true
